import { AppProviders } from '@app/components/app-providers'
import Nav from './components/nav'
import './globals.css'
import { Inter } from 'next/font/google'
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { Box } from '@mui/material';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'test',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${inter.className}`}>
        <AppProviders>
        <Nav />
        {children}
        </AppProviders>
        </body>
    </html>
  )
}
